// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwxvCdu-mZEdgVse6pWY4WR4f71g7OKws',
    appId: '1:737025852662:web:4a5bc8455057d943b658d7',
    messagingSenderId: '737025852662',
    projectId: 'financemanagementapp-c1551',
    authDomain: 'financemanagementapp-c1551.firebaseapp.com',
    storageBucket: 'financemanagementapp-c1551.appspot.com',
    measurementId: 'G-FNTB025ET3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVeoFQ0xQhKxFBQ4BIBbl26FBEVsA4eKQ',
    appId: '1:737025852662:android:d15ef90cf76759e8b658d7',
    messagingSenderId: '737025852662',
    projectId: 'financemanagementapp-c1551',
    storageBucket: 'financemanagementapp-c1551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3xc30M-mWRbeXfSm4O41etorOptHLo5M',
    appId: '1:737025852662:ios:b321430316778976b658d7',
    messagingSenderId: '737025852662',
    projectId: 'financemanagementapp-c1551',
    storageBucket: 'financemanagementapp-c1551.appspot.com',
    iosBundleId: 'com.example.personalFinanceManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3xc30M-mWRbeXfSm4O41etorOptHLo5M',
    appId: '1:737025852662:ios:b321430316778976b658d7',
    messagingSenderId: '737025852662',
    projectId: 'financemanagementapp-c1551',
    storageBucket: 'financemanagementapp-c1551.appspot.com',
    iosBundleId: 'com.example.personalFinanceManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwxvCdu-mZEdgVse6pWY4WR4f71g7OKws',
    appId: '1:737025852662:web:f59a675faca60a6bb658d7',
    messagingSenderId: '737025852662',
    projectId: 'financemanagementapp-c1551',
    authDomain: 'financemanagementapp-c1551.firebaseapp.com',
    storageBucket: 'financemanagementapp-c1551.appspot.com',
    measurementId: 'G-36ZJC90BBN',
  );
}
